format_version: 3
pipelines:
  first-pipeline:
    group: test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      go-agent-git:
        git: https://github.com/vcan92/GoCDStudies.git
    stages:
    - runScript:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_succes: true
        jobs:
          runScript:
            resources:
             - ubuntu
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - chmod +x ./first-pipeline.sh
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - ./first-pipeline.sh
                command: /bin/bash
                run_if: passed
